import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";


import '@/app/ui/global.css';

import {
    NavigationMenu,
    NavigationMenuContent,
    NavigationMenuItem,
    NavigationMenuLink,
    NavigationMenuList,
    NavigationMenuTrigger,
} from "@/components/ui/navigation-menu"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

      <NavigationMenu>
          <NavigationMenuList>
              <NavigationMenuItem>
                  <NavigationMenuTrigger>Item One</NavigationMenuTrigger>
                  <NavigationMenuContent>
                      <NavigationMenuLink>Link</NavigationMenuLink>
                  </NavigationMenuContent>
              </NavigationMenuItem>
          </NavigationMenuList>
      </NavigationMenu>

      {children}
      </body>
    </html>
  );
}



